[package]
name = "realms"
version = "0.0.2"
edition = "2021"

[dependencies]
minifb = "0.27.0"

[dependencies.ril]
version = "0.10.1"
features = ["png", "jpeg", "text", "resize"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

